#pragma once
// Auto-generated by generate_icons_animated.py
// Pilote les animations DWIN en cyclant les index d'icones via VP

#include <Arduino.h>

// VP adresses des widgets icones (a aligner avec dwin_vp_map.h)
#define VP_ICO_WIFI      0x1010
#define VP_ICO_BLE       0x1011
#define VP_ICO_METEO0    0x1020
#define VP_ICO_METEO1    0x1021
#define VP_ICO_METEO2    0x1022
#define VP_ICO_BULB0     0x2010
#define VP_ICO_BULB1     0x2011
#define VP_ICO_BULB2     0x2012
#define VP_ICO_BULB3     0x2013
#define VP_ICO_BULB4     0x2014
#define VP_ICO_BULB5     0x2015
#define VP_ICO_BATTERY   0x3010
#define VP_ICO_SOLAR     0x3011
#define VP_ICO_HEATING   0x4010

// Periodes d'animation en ms
#define ANIM_PERIOD_WIFI    120
#define ANIM_PERIOD_BLE     100
#define ANIM_PERIOD_METEO   150
#define ANIM_PERIOD_BULB    80
#define ANIM_PERIOD_ENERGY  130
#define ANIM_PERIOD_HEAT    100

struct AnimState {
    uint16_t vp;
    uint8_t  first_frame;
    uint8_t  last_frame;
    uint8_t  current;
    uint32_t last_ms;
    uint16_t period_ms;
    bool     active;
};

// Bibliotheques DWIN utilisees :
//  Lib 10 -> WiFi   (frames 0-7=scan, 8-15=connected)
//  Lib 11 -> BLE    (frames 0-7=scan, 8-15=connected)
//  Lib 12 -> Meteo  (frames 0-7=sun, 8-15=rain, 16-23=snow, 24-31=thunder)
//  Lib 13 -> Bulb   (frames 0-7=on_anim, 8-15=pulse)
//  Lib 14 -> Energy (frames 0-7=batt, 8-15=solar, 16-23=victron)
//  Lib 15 -> Nav    (frames 0-7=heat, 8-15=arrow, 16-23=settings)

static AnimState g_anims[] = {
    // VP,           first, last, cur, last_ms, period, active
    {VP_ICO_WIFI,    8,  15, 8,  0, ANIM_PERIOD_WIFI,   true},
    {VP_ICO_BLE,     0,   7, 0,  0, ANIM_PERIOD_BLE,    true},
    {VP_ICO_METEO0,  0,   7, 0,  0, ANIM_PERIOD_METEO,  true},
    {VP_ICO_METEO1,  0,   7, 0,  0, ANIM_PERIOD_METEO,  true},
    {VP_ICO_METEO2,  0,   7, 0,  0, ANIM_PERIOD_METEO,  true},
    {VP_ICO_BATTERY, 0,   7, 0,  0, ANIM_PERIOD_ENERGY, false},
    {VP_ICO_SOLAR,   8,  15, 8,  0, ANIM_PERIOD_ENERGY, true},
    {VP_ICO_HEATING, 0,   7, 0,  0, ANIM_PERIOD_HEAT,   false},
};
static const uint8_t N_ANIMS = sizeof(g_anims)/sizeof(g_anims[0]);

// Appeler dans setup() apres init DWIN
inline void anim_init() {
    for(auto& a : g_anims) {
        a.current  = a.first_frame;
        a.last_ms  = millis();
    }
}

// Appeler dans loop() - envoie la commande VP si la frame a change
inline void anim_tick(HardwareSerial& dwin_serial) {
    uint32_t now = millis();
    for(auto& a : g_anims) {
        if(!a.active) continue;
        if(now - a.last_ms >= a.period_ms) {
            a.last_ms = now;
            a.current++;
            if(a.current > a.last_frame) a.current = a.first_frame;
            // Commande DWIN : 5A A5 05 82 VP_H VP_L 00 FRAME
            uint8_t cmd[8] = {
                0x5A, 0xA5, 0x05, 0x82,
                (uint8_t)(a.vp >> 8), (uint8_t)(a.vp & 0xFF),
                0x00, a.current
            };
            dwin_serial.write(cmd, 8);
        }
    }
}

// Helpers pour changer le groupe d'animation selon l'etat systeme

inline void anim_set_wifi(bool connected) {
    g_anims[0].first_frame = connected ? 8 : 0;
    g_anims[0].last_frame  = connected ? 15 : 7;
    g_anims[0].current     = g_anims[0].first_frame;
}

inline void anim_set_ble(bool connected) {
    g_anims[1].first_frame = connected ? 8 : 0;
    g_anims[1].last_frame  = connected ? 15 : 7;
    g_anims[1].current     = g_anims[1].first_frame;
}

// code: 0=sun 1=rain 2=snow 3=thunder
inline void anim_set_weather(uint8_t ico_idx, uint8_t code) {
    if(ico_idx >= 3) return;
    uint8_t base = code * 8;
    g_anims[2+ico_idx].first_frame = base;
    g_anims[2+ico_idx].last_frame  = base+7;
    g_anims[2+ico_idx].current     = base;
}

inline void anim_set_battery_charging(bool charging) {
    g_anims[5].active = charging;
}

inline void anim_set_heating(bool on) {
    g_anims[7].active = on;
}
