// Auto-generated by export_lvgl_icons.py
// Moteur d'animation LVGL : cycle de frames via lv_timer
#pragma once
#include "lvgl.h"
#include "lvgl_icons_data.h"

// ─────────────────────────────────────────────────────────────────────────────
// Structure d'une animation
// ─────────────────────────────────────────────────────────────────────────────
typedef struct {
    lv_obj_t*              img_obj;       // widget lv_img cible
    const lv_img_dsc_t**   frames;        // tableau de pointeurs frames
    uint8_t                frame_count;
    uint8_t                current_frame;
    lv_timer_t*            timer;
    bool                   active;
} lvgl_anim_t;

#define MAX_ANIMS 16
static lvgl_anim_t _anims[MAX_ANIMS];
static uint8_t     _anim_count = 0;

// ─────────────────────────────────────────────────────────────────────────────
// Callback interne du timer
// ─────────────────────────────────────────────────────────────────────────────
static void _anim_timer_cb(lv_timer_t* timer) {
    lvgl_anim_t* a = (lvgl_anim_t*)timer->user_data;
    if (!a->active || !a->img_obj) return;
    a->current_frame = (a->current_frame + 1) % a->frame_count;
    lv_img_set_src(a->img_obj, a->frames[a->current_frame]);
}

// ─────────────────────────────────────────────────────────────────────────────
// API publique
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Enregistrer une animation sur un widget lv_img
 * @return index de l'animation (-1 si erreur)
 */
static inline int lvgl_anim_register(
    lv_obj_t* img_obj,
    const lv_img_dsc_t** frames,
    uint8_t frame_count,
    uint32_t period_ms)
{
    if (_anim_count >= MAX_ANIMS) return -1;
    lvgl_anim_t* a  = &_anims[_anim_count];
    a->img_obj      = img_obj;
    a->frames       = frames;
    a->frame_count  = frame_count;
    a->current_frame= 0;
    a->active       = true;
    a->timer        = lv_timer_create(_anim_timer_cb, period_ms, a);
    lv_img_set_src(img_obj, frames[0]);
    return _anim_count++;
}

/** Activer / desactiver une animation */
static inline void lvgl_anim_set_active(int idx, bool active) {
    if (idx < 0 || idx >= _anim_count) return;
    _anims[idx].active = active;
    if (active) lv_timer_resume(_anims[idx].timer);
    else        lv_timer_pause(_anims[idx].timer);
}

/** Changer le groupe de frames a la volee (ex: wifi_scan -> wifi_ok) */
static inline void lvgl_anim_set_frames(
    int idx,
    const lv_img_dsc_t** frames,
    uint8_t frame_count,
    uint32_t period_ms)
{
    if (idx < 0 || idx >= _anim_count) return;
    _anims[idx].frames       = frames;
    _anims[idx].frame_count  = frame_count;
    _anims[idx].current_frame= 0;
    lv_timer_set_period(_anims[idx].timer, period_ms);
    lv_img_set_src(_anims[idx].img_obj, frames[0]);
}

/** Stopper toutes les animations (avant changement de page) */
static inline void lvgl_anim_stop_all(void) {
    for (int i = 0; i < _anim_count; i++)
        lv_timer_pause(_anims[i].timer);
}

/** Reprendre toutes les animations */
static inline void lvgl_anim_resume_all(void) {
    for (int i = 0; i < _anim_count; i++)
        if (_anims[i].active) lv_timer_resume(_anims[i].timer);
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers haut niveau pour le dashboard van
// ─────────────────────────────────────────────────────────────────────────────

// Index des animations (ordre d'enregistrement dans van_ui_init)
#define ANIM_IDX_WIFI      0
#define ANIM_IDX_BLE       1
#define ANIM_IDX_WEATHER0  2
#define ANIM_IDX_WEATHER1  3
#define ANIM_IDX_WEATHER2  4
#define ANIM_IDX_BATTERY   5
#define ANIM_IDX_SOLAR     6
#define ANIM_IDX_HEATING   7

static inline void van_anim_set_wifi(bool connected) {
    if (connected)
        lvgl_anim_set_frames(ANIM_IDX_WIFI,
            (const lv_img_dsc_t**)frames_wifi_ok,
            FRAMES_WIFI_OK_COUNT, 200);
    else
        lvgl_anim_set_frames(ANIM_IDX_WIFI,
            (const lv_img_dsc_t**)frames_wifi_scan,
            FRAMES_WIFI_SCAN_COUNT, 120);
}

static inline void van_anim_set_ble(bool connected) {
    if (connected)
        lvgl_anim_set_frames(ANIM_IDX_BLE,
            (const lv_img_dsc_t**)frames_ble_ok,
            FRAMES_BLE_OK_COUNT, 300);
    else
        lvgl_anim_set_frames(ANIM_IDX_BLE,
            (const lv_img_dsc_t**)frames_ble_scan,
            FRAMES_BLE_SCAN_COUNT, 100);
}

// Convertit un code OWM en index 0-3 (sun/rain/snow/storm)
static inline uint8_t owm_to_anim_code(int owm_id) {
    if (owm_id >= 200 && owm_id < 300) return 3; // orage
    if (owm_id >= 300 && owm_id < 700) return 1; // pluie/bruine
    if (owm_id >= 700 && owm_id < 800) return 1; // brume -> pluie
    if (owm_id == 800)                 return 0; // ciel clair
    if (owm_id >= 801 && owm_id < 900) return 0; // nuageux -> soleil
    if (owm_id >= 600 && owm_id < 700) return 2; // neige
    return 0;
}

// code: 0=sun 1=rain 2=snow 3=storm
static inline void van_anim_set_weather(uint8_t slot, uint8_t code) {
    static const lv_img_dsc_t** weather_frames[] = {
        (const lv_img_dsc_t**)frames_weather_sun,
        (const lv_img_dsc_t**)frames_weather_rain,
        (const lv_img_dsc_t**)frames_weather_snow,
        (const lv_img_dsc_t**)frames_weather_storm,
    };
    static const uint8_t weather_counts[] = {
        FRAMES_WEATHER_SUN_COUNT,
        FRAMES_WEATHER_RAIN_COUNT,
        FRAMES_WEATHER_SNOW_COUNT,
        FRAMES_WEATHER_STORM_COUNT,
    };
    static const uint32_t weather_periods[] = {150, 120, 180, 80};
    if (code > 3 || slot > 2) return;
    lvgl_anim_set_frames(ANIM_IDX_WEATHER0 + slot,
        weather_frames[code], weather_counts[code], weather_periods[code]);
}

static inline void van_anim_set_battery_charging(bool charging) {
    lvgl_anim_set_active(ANIM_IDX_BATTERY, charging);
}

static inline void van_anim_set_heating(bool on) {
    lvgl_anim_set_active(ANIM_IDX_HEATING, on);
}
