// Auto-generated by export_lvgl_icons.py
// Initialisation des animations LVGL pour le dashboard van
// Inclure apres la creation des widgets lv_img dans page_home / page_energy / etc.

#include "lvgl_anim_icons.h"

// ─────────────────────────────────────────────────────────────────────────────
// Objets lv_img crees dans les pages (a declarer extern dans les .h de pages)
// ─────────────────────────────────────────────────────────────────────────────
extern lv_obj_t* img_wifi;       // page_home.cpp
extern lv_obj_t* img_ble;        // page_home.cpp
extern lv_obj_t* img_weather[3]; // page_home.cpp
extern lv_obj_t* img_battery;    // page_energy.cpp
extern lv_obj_t* img_solar;      // page_energy.cpp
extern lv_obj_t* img_heating;    // page_heating.cpp

/**
 * Appeler APRES lv_init() et la creation de tous les widgets
 * Enregistre les animations dans l'ordre (ANIM_IDX_*)
 */
void van_anims_init(void) {
    // 0 - WiFi (demarre en mode scan)
    lvgl_anim_register(img_wifi,
        (const lv_img_dsc_t**)frames_wifi_scan,
        FRAMES_WIFI_SCAN_COUNT, 120);

    // 1 - BLE (demarre en mode scan)
    lvgl_anim_register(img_ble,
        (const lv_img_dsc_t**)frames_ble_scan,
        FRAMES_BLE_SCAN_COUNT, 100);

    // 2,3,4 - Meteo 3 jours (soleil par defaut)
    for (int i = 0; i < 3; i++) {
        lvgl_anim_register(img_weather[i],
            (const lv_img_dsc_t**)frames_weather_sun,
            FRAMES_WEATHER_SUN_COUNT, 150);
    }

    // 5 - Batterie (inactif par defaut, active si charge detectee)
    lvgl_anim_register(img_battery,
        (const lv_img_dsc_t**)frames_batt_charge,
        FRAMES_BATT_CHARGE_COUNT, 130);
    lvgl_anim_set_active(ANIM_IDX_BATTERY, false);

    // 6 - Solaire (toujours actif)
    lvgl_anim_register(img_solar,
        (const lv_img_dsc_t**)frames_solar_flux,
        FRAMES_SOLAR_FLUX_COUNT, 130);

    // 7 - Chauffage (inactif par defaut)
    lvgl_anim_register(img_heating,
        (const lv_img_dsc_t**)frames_heat_flame,
        FRAMES_HEAT_FLAME_COUNT, 100);
    lvgl_anim_set_active(ANIM_IDX_HEATING, false);
}
